
sycl1.2.1:
	icpx -O3 -std=c++17 -fsycl -sycl-std=2017 ../hello_world_1.2.1.cpp -o hello_world_1.2.1.out
  
sycl2020:
	icpx -O3 -std=c++17 -fsycl -sycl-std=2020 ../hello_world_2020.cpp -o hello_world_2020.out
