

sycl1.2.1:
	compute++ -O3 -std=c++14 -DSYCL_LANGUAGE_VERSION=2017 -sycl-driver -no-serial-memop -lComputeCpp ../hello_world_1.2.1.cpp -o hello_world_1.2.1.out
  
sycl2020:
	compute++ -O3 -std=c++17 -DSYCL_LANGUAGE_VERSION=2020 -sycl-driver -no-serial-memop -lComputeCpp ../hello_world_2020.cpp -o hello_world_2020.out
